"""
Django settings for foodwast project.

In this settings.py file, various configurations and settings for the Django project are defined.

The BASE_DIR variable is used to build file paths inside the project.
SECRET_KEY is the secret key used to secure the Django project.
DEBUG is set to True to enable debugging in development mode. This should be set to False in production for security.
ALLOWED_HOSTS is an empty list, which means the Django project can be accessed from any host during development.
INSTALLED_APPS contains the list of installed Django applications for this project.
MIDDLEWARE is a list of middleware classes used to process requests and responses.
ROOT_URLCONF specifies the URL configuration for the project.
TEMPLATES defines the template settings for the project.
WSGI_APPLICATION points to the WSGI application used to serve the project.
DATABASES contains the database settings for the project. In this case, MySQL is used as the database engine.
AUTH_PASSWORD_VALIDATORS is a list of password validation rules for user passwords.
LANGUAGE_CODE and TIME_ZONE are used for internationalization settings.
STATIC_URL and STATIC_ROOT are used to handle static files like CSS, JavaScript, and images in the project.
STATICFILES_DIRS contains additional directories for static files.
MEDIA_URL and MEDIA_ROOT are used to handle media files like user uploads in the project.


Generated by 'django-admin startproject' using Django 3.0.3.
For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# Get the base directory of the project using 'os.path.dirname' twice on '__file__'
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The secret key used for cryptographic signing in Django. In production, this should be kept secret.
SECRET_KEY = '0h%8b!!5$gv2=og_y)2a$f*gxm-5@z0=2_@$!x4-w#1hhclsof'

# SECURITY WARNING: don't run with debug turned on in production!
# Whether the Django app is running in debug mode. Should be False in production.
DEBUG = True

# List of host/domain names that this Django app can server
ALLOWED_HOSTS = []


# Application definition
# List of all installed Django applications for this project.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'food',
]

# Middleware classes used in the Django app.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# URL configurations for this Django project.
ROOT_URLCONF = 'foodwast.urls'

# Template configurations for this Django project.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [((os.path.join(BASE_DIR,'assets/templates')))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ASGI application for this Django project.
WSGI_APPLICATION = 'foodwast.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # SQLite database file location
        'NAME': os.path.join(BASE_DIR, 'food.db'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

# Password validators used to validate user passwords.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

# Language code for this Django project.
LANGUAGE_CODE = 'en-us'
# Time zone for this Django project.
TIME_ZONE = 'UTC'
# Enable Django's internationalization system.
USE_I18N = True
# Enable Django's localization system.
USE_L10N = True
# Use the timezone setting.
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# URL for serving static files (CSS, JavaScript, Images).
STATIC_URL = '/static/'
# Directory where static files will be collected during deployment.
STATIC_ROOT = os.path.join(BASE_DIR, 'static-files')
# Additional locations of static files for the development server.
STATICFILES_DIRS= [os.path.join(BASE_DIR,'assets/'),]
# URL for serving media files (user-uploaded content).
MEDIA_URL = '/media/'
# Directory where media files will be stored.
MEDIA_ROOT = os.path.join(BASE_DIR,'assets/media')
